FROM alpine

RUN apk add -U --upgrade --no-cache \
        libdbi-drivers \
        paho-mqtt-c \
        py3-syslog-ng \
        syslog-ng \
        syslog-ng-add-contextual-data \
        syslog-ng-amqp \
        syslog-ng-graphite \
        syslog-ng-http \ 
        syslog-ng-json \
        syslog-ng-map-value-pairs \
        syslog-ng-redis \
        syslog-ng-scl \
        syslog-ng-sql \
        syslog-ng-stardate \
        syslog-ng-stomp \
        syslog-ng-tags-parser \
        syslog-ng-xml && \
    rm -rf \
        /tmp/*