FROM alpine

ARG TARGETPLATFORM
ARG GCLOUD_CLI_URL_ARM=https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-linux-arm.tar.gz
ARG GCLOUD_CLI_URL_X64=https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-linux-x86_64.tar.gz

RUN apk add -U --upgrade --no-cache syslog-ng-amqp syslog-ng-dev syslog-ng-doc syslog-ng-examples syslogng-graphite syslog-ng-http syslog-ng-json syslog-ng-map-value-pairs syslog-ng-openrc syslog-ng-redis syslog-ng-scl syslog-ng-sql syslog-ng-stardate syslog-ng-stomp syslog-ng-tags-parser syslog-ng-xml python3 && \
    rm -rfv /tmp/* /var/cache/apt/ /var/lib/apt/

RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then \
        wget ${GCLOUD_CLI_URL_X64} -O gcloud.tar.gz; \
    elif [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
        wget ${GCLOUD_CLI_URL_ARM} -O gcloud.tar.gz; \
    else \
        echo "Unsupported platform: $TARGETPLATFORM" && exit 1; \
    fi && \
    tar -xzf gcloud.tar.gz && rm -f gcloud.tar.gz && \
    ./google-cloud-sdk/install.sh --quiet --path-update true --usage-reporting false\




