# Create and publish a Container image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: '2.0.11'
      versionqb:
        description: 'version'
        required: true
        default: '5.1.0'
  schedule: 
    - cron: '0 2 * * 0'
      inputs:
        version:
          description: 'version'
          required: true
          default: '2.0.11'
        versionqb:
          description: 'version'
          required: true
          default: '5.1.0'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Image name
        id: image_name
        run: |
          FILENAME="${{ github.workflow }}"
          echo "name=$(basename -- ${FILENAME%.yml})" >> "$GITHUB_OUTPUT"
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ steps.image_name.outputs.name }}

      - name: Set version variable
        id: set_version
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            echo "version=2.0.11" >> "$GITHUB_ENV"
          else
            echo "version=${{ github.event.inputs.version  }}" >> "$GITHUB_ENV"
          fi
          if [ "${{ github.event_name }}" = "schedule" ]; then
            echo "versionqb=5.1.0" >> "$GITHUB_ENV"
          else
            echo "versionqb=${{ github.event.inputs.versionqb  }}" >> "$GITHUB_ENV"
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ steps.image_name.outputs.name }}
          file: ./${{ steps.image_name.outputs.name }}/Containerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ steps.set_version.outputs.version }}
            VERSIONQB=${{ steps.set_version.outputs.versionqb }}
